# -*- coding: utf-8 -*-
"""FSS_BK_FULL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NncMUnY0NejmMnGmw4vWq1WaZlML3W5B
"""

import pandas as pd
import numpy as np
import requests
import json
import os
from dotenv import load_dotenv
# import urllib.parse

load_dotenv(os.path.join(os.path.dirname(__file__), '..', '.env'))
FSS_API_KEY = os.environ['FACTIVA_SENTIMENT_API_KEY']

from datetime import date, timedelta
from time import sleep
from google.colab import files, drive
drive.mount('/content/drive', force_remount=True)

# # to download current company codes: FOLDED INTO get_codes() below

# # Get company codes
# url_ = 'https://api.dowjones.com/fss/taxonomies/companies?format=json'

# headers = {
#     'user-key': FSS_API_KEY
# }

# response = requests.get(url_, headers=headers)
# response.raise_for_status()  # Raise an exception for bad status codes
# print(response.json())
# resp = response.json()
# get_job_url = resp['download_urls'][0]
# get_job_resp = requests.get(get_job_url, headers=headers)

# lines = get_job_resp.text.strip().split('\n')
# to_df = []

# for line in lines:
#   if line:
#     try:
#       json_obj = json.loads(line)
#       to_df.append(json_obj)
#     except json.JSONDecodeError as line_e:
#       print(f"Error decoding line: {line_e} - Line: {line}")

# test = pd.DataFrame(to_df)

def get_codes(reg=['USA'], new=False, save=False):

  if new:
    # Get company codes from FSS
    url_ = 'https://api.dowjones.com/fss/taxonomies/companies?format=json'

    headers = {
        'user-key': FSS_API_KEY
    }

    response = requests.get(url_, headers=headers)
    response.raise_for_status()  # Raise an exception for bad status codes
    print(response.json())
    resp = response.json()
    get_job_url = resp['download_urls'][0]
    get_job_resp = requests.get(get_job_url, headers=headers)

    lines = get_job_resp.text.strip().split('\n')
    to_df = []

    for line in lines:
      if line:
        try:
          json_obj = json.loads(line)
          to_df.append(json_obj)
        except json.JSONDecodeError as line_e:
          print(f"Error decoding line: {line_e} - Line: {line}")

    codes = pd.DataFrame(to_df)

    if save:
      codes.to_csv('/content/drive/MyDrive/FSS_files/FSS_company_codes.csv', encoding = 'utf-8-sig', index=False)

  else:
    # Get company codes from file
    codes = pd.read_csv('/content/drive/MyDrive/FSS_files/FSS_company_codes.csv', low_memory=False)

  codes = codes[codes.Region.isin(reg)]
  codes = codes.reset_index(drop=True)

  return codes

def get_industries(df, limit=30):
  counts = df.IndustryDescriptor.value_counts()
  counts = counts.reset_index(drop=False)

  out = {'industry': [],
         'count': []
         }

  for i in range(len(counts)):
    if counts.loc[i, 'count'] >= limit:
      out['industry'].append(counts.loc[i, 'IndustryDescriptor'])
      out['count'].append(counts.loc[i, 'count'])

  return out

def get_firms(dic, df):

  dic['company_code'] = []
  dic['company_name'] = []
  dic['ticker'] = []
  dic['status'] = []
  dic['list_status'] = []

  for ind in dic['industry']:
    code = df[df.IndustryDescriptor == ind]
    dic['company_code'].append(code._CompanyCode.to_list())
    dic['company_name'].append(code.CompanyName.to_list())
    dic['ticker'].append(code.ExchangeTicker.to_list())
    dic['status'].append(code.Status.to_list())
    dic['list_status'].append(code.ListStatus.to_list())

  return dic

def FSS_industries(reg=['USA'], new=False, save=False, limit=30):
  codes = get_codes(reg, new, save)
  industries = get_industries(codes, limit)
  firms = get_firms(industries, codes)

  out = pd.DataFrame(firms)
  out['num_active'] = [x.count('A') for x in out['status']]
  out['num_listed'] = [x.count('L') for x in out['list_status']]

  return out

def FSS_call(firms, start, end):

  url = 'https://api.dowjones.com/fss/extractions/'

  headers = {
      'Content-Type': 'application/json',
      'user-key': os.environ['FACTIVA_SENTIMENT_API_KEY']
  }

  payload = {
      "query": {
          "companies": firms,
          "start": start,
          "end": end,
          "articles": False,
          "format": "json"
      }
  }

  if not end:
    del payload['query']['end']

  print(headers)
  print(payload)

  try:
    response = requests.post(url, headers=headers, data=json.dumps(payload))
    response.raise_for_status()  # Raise an exception for bad status codes
    print(f"Response text: {response.text}")
  except requests.exceptions.RequestException as e:
      print(f"An error occurred: {e}")
      if response is not None:
          print(f"Response status code: {response.status_code}")
          print(f"Response text: {response.text}")

  if response.status_code != 201:
      print("ERROR: An error occurred creating an extraction: " + response.text)
  else:
      resp = response.json()
      job_id = resp['extraction_id']
      currentState = resp['state']
      while currentState != 'JOB_STATE_DONE':
        sleep(10)
        get_job_url = f'{url}{job_id}'
        get_job_resp = requests.get(get_job_url, headers=headers)
        get_job_resp_dict = get_job_resp.json()
        print("Current state is: " + get_job_resp_dict['state'])
        # print(get_job_resp_dict)
        currentState = get_job_resp_dict['state']
      if 'destination' in get_job_resp_dict:
        self_link = get_job_resp_dict['destination']
        get_data_resp = requests.get(self_link[0], headers=headers)
        print(get_data_resp)
        lines = get_data_resp.text.strip().split('\n')
        to_df = []
        for line in lines:
          if line:
            try:
              json_obj = json.loads(line)
              to_df.append(json_obj)
            except json.JSONDecodeError as line_e:
              print(f"Error decoding line: {line_e} - Line: {line}")
  if len(to_df) > 0:
    return pd.DataFrame(to_df)
  else:
    print(f'No Data Returned: {to_df}')

def get_industry_changes(start, end, bottom=None): #this is the longer script below
  inds = FSS_industries()

  out = {}
  # start = '2025-01-01'
  # end = '2025-04-01'
  ind = inds[bottom:].reset_index()

  for i in range(len(ind)):
    sleep(20)
    firms = ind.loc[i, 'company_code']
    print(f"{len(firms)}: {firms}")
    get_firms = FSS_call(firms, start, end)

    mean_score = get_firms[['score_date', 'score']].groupby('score_date').mean().reset_index(drop=False)
    min_score = get_firms.groupby('score_date')['score'].min().to_list()
    max_score = get_firms.groupby('score_date')['score'].max().to_list()

    mean_score.index = pd.to_datetime(mean_score['score_date'])

    # daily percent change
    mean_score['daily_pct_change'] = mean_score['score'].pct_change()

    # weekly change
    mean_score['7_day_change'] = mean_score['score'].shift(7)
    mean_score['7_day_comp'] = mean_score['score_date'].shift(7)
    mean_score['weekly_pct_change'] = (mean_score['score'] - mean_score['7_day_change'])/ mean_score['7_day_change']

    # monthly change
    mean_score['30_day_change'] = mean_score['score'].shift(30)
    mean_score['30_day_comp'] = mean_score['score_date'].shift(30)
    mean_score['monthly_pct_change'] = (mean_score['score'] - mean_score['30_day_change'])/ mean_score['30_day_change']

    mean_score['min_score'] = min_score
    mean_score['max_score'] = max_score

    out[ind.loc[i, 'industry']] = {'ind_score_changes': mean_score, # pd.DataFrame
                                    'company_codes': firms, # list
                                    'company_scores': get_firms #pd.DataFramea
                                    }
    print(f"DONE: {ind.loc[i, 'industry']}")

  return out

def change_since_start(score_dict, start, end):
  since_changes = {}

  for k in score_dict.keys():
    df = score_dict[k]['ind_score_changes'].copy()
    df = df.reset_index(drop=True)
    first = df.loc[0, 'score']
    since_changes['date'] = df['score_date']
    since_changes[k] = [(df.loc[i, 'score'] - first)/first for i in range(len(df))]

  return since_changes


# USE THIS TO GET COMPANY LEVEL INFORMATION
def FSS_call_chunk(company_codes_list, start, end, limit=1000):

    all_results = []
    list_length = len(company_codes_list)

    if list_length > limit:
        # Calculate the number of chunks needed
        num_chunks = (list_length + limit - 1) // limit  # Ceiling division

        for i in range(num_chunks):
            start_index = i * limit
            end_index = min((i + 1) * limit, list_length)
            chunk = company_codes_list[start_index:end_index]
            print(f"Processing chunk {i+1}/{num_chunks} with {len(chunk)} codes.")
            chunk_df = FSS_call(chunk, start, end)
            all_results.append(chunk_df)
    else:
        print(f"Processing single chunk with {list_length} codes.")
        single_df = FSS_call(company_codes_list, start, end)
        all_results.append(single_df)

    # Concatenate all dataframes into a single one
    if all_results:
        return pd.concat(all_results, ignore_index=True)
    else:
        return pd.DataFrame()

def save_json(out, file_path):
    # --- Conversion Logic ---
    # Create a new dictionary to store the serializable version
    serializable_out = {}

    for industry_key, industry_data_dict in out.items():
        # Each 'industry_data_dict' is the inner dictionary like {'ind_score_changes': ..., 'company_codes': ...}
        serializable_inner_dict = {}
        for sub_key, sub_value in industry_data_dict.items():
            if isinstance(sub_value, pd.DataFrame):
                # Convert DataFrame to JSON string
                serializable_inner_dict[sub_key] = sub_value.to_json(orient='records', indent=4)
            else:
                # Keep other values (lists, strings, numbers) as they are
                serializable_inner_dict[sub_key] = sub_value
        serializable_out[industry_key] = serializable_inner_dict

    # # --- Debugging check (optional, but good practice) ---
    # print("\n--- Structure of 'serializable_out' before json.dump() ---")
    # for k, v in serializable_out.items():
    #     print(f"Top-level Key: {k}, Type: {type(v)}")
    #     if isinstance(v, dict):
    #         for nk, nv in v.items():
    #             print(f"  Inner Key: {nk}, Type: {type(nv)}")
    # print("-----------------------------------------------------")


    # Save the entire dictionary as a JSON file
    # Assuming you've already mounted your Google Drive: drive.mount('/content/drive')
    # file_path = '/content/drive/MyDrive/FSS_files/fss_q1_select_company_data.json'
    with open(file_path, 'w') as f:
        json.dump(serializable_out, f, indent=4)

    print(f"\nFile saved successfully to: {file_path}")

    return serializable_out

def reload_json(file_path):
# --- Loading Back (for demonstration) ---
    print("\n--- Loading the JSON file back ---")
    with open(file_path, 'r') as f:
        loaded_data = json.load(f)

    reconstructed_out = {}
    for industry_key, industry_data_dict_str in loaded_data.items():
        reconstructed_inner_dict = {}
        for sub_key, sub_value_str in industry_data_dict_str.items():
            if sub_key in ['ind_score_changes', 'company_scores']: # Identify DataFrame keys
                reconstructed_inner_dict[sub_key] = pd.read_json(sub_value_str)
            else:
                reconstructed_inner_dict[sub_key] = sub_value_str
        reconstructed_out[industry_key] = reconstructed_inner_dict

    print("\nReconstructed 'out' structure for 'Technology' industry:")
    print("Type of 'ind_score_changes':", type(reconstructed_out['Software']['ind_score_changes']))
    print(reconstructed_out['Software']['ind_score_changes'])
    print("\nType of 'company_scores':", type(reconstructed_out['Software']['company_scores']))
    print(reconstructed_out['Software']['company_scores'])
    print("\nType of 'company_codes':", type(reconstructed_out['Software']['company_codes']))

    print(reconstructed_out['Software']['company_codes'])

def prop_neg_article(df):
  df_ = df.copy()

  df['negative_article_count'] = df['negative_article_count'].astype(int)
  df['total_article_count'] = df['total_article_count'].astype(int)
  df['prop_negative_article'] = round(df['negative_article_count'] / get_firms['total_article_count']*100, 2)

  return df

# GET SOFTWARE AND RETAIL COMPANY LISTS
inds = FSS_industries(new=False, save=False) #<<<<<-------CALL TO GET INDUSTRIES

software = [] # THESE COULD BE DIFFERENT, BUT GOOD FOR NOW. COULD GENERALIZE TO RETURN CO_DF
retail = []
for i in inds.industry:
  if 'software' in i.lower():
    software.append(i)
  if 'retail' in i.lower():
    retail.append(i)

retail.remove('Retail REITs') # return a list of possible matches to check first, then move on the exploding them

soft = inds[inds.industry.isin(software)][['industry', 'num_active', 'num_listed']]
reti = inds[inds.industry.isin(retail)][['industry', 'num_active', 'num_listed']]


ret_soft = pd.concat([reti, soft])
ret_soft.columns = ret_soft.columns.str.strip()

all_inds = software + retail
all = inds[inds.industry.isin(all_inds)]

# List of columns that contain nested lists
cols_to_explode = ['company_name', 'status', 'list_status', 'ticker', 'company_code']

# Explode them all at once
new_df = all.explode(cols_to_explode)

# Optional: Reset the index if you want a clean 0, 1, 2... sequence
new_df = new_df.reset_index(drop=True)

co_df = new_df[['industry','company_name', 'status', 'list_status', 'ticker', 'company_code']]
co_df = co_df[co_df.status == 'A']

co_df #TAKE THIS LIST TO S&P FOR CODES....FOR NOW USE CODES S&P SENT....API INTEGRATION LATER WOULD BE GOOD





# USE THIS TO SAVE THE SEGMENTS OF COMPANIES
# TO MAKE SMALLER LISTS TO SEND TO S&P
# ALL = bk_companyList_MASTER.csv (from S&P with codes)
SAVE_SEGMENTS = False

if SAVE_SEGMENTS:
  filepath = '/content/drive/MyDrive/FSS_files/bankruptcy_test_companies/' #<<<----- FILES BELOW ARE HERE

  for x in ['all', 'all_listed', 'all_unlisted', 'retail_listed', 'retail_unlisted', 'software_listed', 'software_unlisted']:
    file = f'bk_companyList_{x}.csv'
    name = os.path.join(filepath, file)
    if x == 'all':
      co_df.to_csv(name, encoding = 'utf-8-sig', index=False)
    elif x == 'all_listed':
      co_df[co_df.list_status == 'L'].to_csv(name, encoding = 'utf-8-sig', index=False)
    elif x == 'all_unlisted':
      co_df[co_df.list_status == 'UL'].to_csv(name, encoding = 'utf-8-sig', index=False)
    elif x == 'retail_listed':
      co_df[(co_df.list_status == 'L') & (co_df.industry.isin(retail))].to_csv(name, encoding = 'utf-8-sig', index=False)
    elif x == 'retail_unlisted':
      co_df[(co_df.list_status == 'UL') & (co_df.industry.isin(retail))].to_csv(name, encoding = 'utf-8-sig', index=False)
    elif x == 'software_listed':
      co_df[(co_df.list_status == 'L') & (co_df.industry.isin(software))].to_csv(name, encoding = 'utf-8-sig', index=False)
    elif x == 'software_unlisted':
      co_df[(co_df.list_status == 'UL') & (co_df.industry.isin(retail))].to_csv(name, encoding = 'utf-8-sig', index=False)

sandp.columns

# FOR THE MERGE FROM S&P -- LOAD S&P DATA
path = '/content/drive/MyDrive/FSS_files/FSS_Product_TESTS/'
sandp = pd.read_csv(f'{path}SPGlobal_Export_4-3-2026_POC_LISTED_RETAIL_V6.csv') # PULLED FROM S&P PLATFORM SCREENER

sp_english = zip(sandp.columns, sandp.iloc[1])
sp_english = [f'{i}_{e}' for i,e in sp_english]

# We search the whole dataframe for the string and get the first occurrence
header_idx = sandp[sandp.eq("SP_ENTITY_NAME").any(axis=1)].index[0]
time_idx = header_idx + 1

header_labels = sandp.iloc[header_idx].fillna('').astype(str)
time_labels = sandp.iloc[time_idx].fillna('').astype(str)

sp_english = zip(sandp.columns, sandp.iloc[time_idx])
sp_english = [f'{i}&&{e}' for i,e in sp_english] #----> && seperator for english column names

time_cols = []
for header, time in zip(header_labels, time_labels):
  if time == '':
    time_cols.append(header)
  else:
    if 'quarter' in time.lower():
      time_cols.append(f"{header}_Q")
    elif 'year' in time.lower():
      time_cols.append(f"{header}_Y")
    else:
      time_cols.append(f'{header}_{time}')

sandp.columns = sandp.iloc[header_idx]
sandp = sandp.iloc[header_idx + 1:, :]
sandp = sandp[sandp["SP_ENTITY_NAME"].notna()]

sandp.columns = time_cols
sandp.reset_index(inplace=True, drop=True)

sandp.head()

# FOR THE MERGE FROM S&P -- LOAD S&P DATA
# path = '/content/drive/MyDrive/FSS_files/FSS_Product_TESTS/'
# sandp = pd.read_csv(f'{path}SPGlobal_Export_4-3-2026_POC_LISTED_RETAIL_V3.csv') # PULLED FROM S&P PLATFORM SCREENER

# sp_english = zip(sandp.columns, sandp.iloc[1])
# sp_english = [f'{i}_{e}' for i,e in sp_english]

# # We search the whole dataframe for the string and get the first occurrence
# header_idx = sandp[sandp.eq("SP_ENTITY_NAME").any(axis=1)].index[0]

# sandp.columns = sandp.iloc[header_idx]
# sandp = sandp.iloc[header_idx + 1].reset_index(drop=True)
# sandp = sandp[sandp["SP_ENTITY_NAME"].notna()]
# # sandp = sandp[3:]
# # sandp.reset_index(drop=True, inplace=True)


# LOAD COMPANY IDENTIFIERS FOR FSS AND S&P
fss_list = pd.read_csv(f'{path}bk_companyList_MASTER.csv') # data needed to merge. MAY NEED UPDATED LIST AT SOME POINT

ids = sandp['SP_CIQ_ID'].dropna().tolist()
# fss_retail_listed = fss_list[fss_list.]
# len(fss_retail_listed)

retail = list(set([f for f in fss_list.industry_FSS if 'retail' in f.lower()]))
ret = fss_list[(fss_list.industry_FSS.isin(retail)) & (fss_list.list_status_FSS == 'L')]

fss_retail_listed = ret.merge(sandp, on='SP_CIQ_ID', how='left')
# fss_retail_listed.to_csv(path+'FSS_SandP_retail_listed.csv', index=False)

fss_retail_listed



if len(fss_retail_listed) > 0:
  print('yes')

# GENERATING SCORES FOR FSS BASED ON LISTED RETAIL COMPANIES

# read in list of companies from S&P merge:
if len(fss_retail_listed) > 0:
  retail_co_SPmerge = fss_retail_listed.copy()
else:
  retail_co_SPmerge = pd.read_csv('/content/drive/MyDrive/FSS_files/FSS_Product_TESTS/FSS_SandP_retail_listed.csv') # fss_retail_listed ABOVE


company_pull_list = retail_co_SPmerge.company_code_FSS.to_list() # list of companies after merge with S&P to pull FSS scores

# from datetime import date, timedelta
# import json

# x = date.today()
# x.isoformat()

# company_pull_list = retail_co_SPmerge.company_code_FSS.to_list()

# USE THIS FOR THE FSS SCORES PULL....

# # for ch, chunk in enumerate(chunks):
# for i_ in range(7,8):
#     out = {}
# start = '2025-11-01'
# end = '2026-02-26'

end = date.today()
start = end - timedelta(days=5)
end = end.isoformat()
start = start.isoformat()

#     ind = chunks[i_].reset_index() # limited size from matched_fss_inds

#     for i in range(len(ind)):
# firms = ind.loc[i, 'company_code']

firms = company_pull_list
# tickers = ind.loc[i, 'ticker']
print(f"{len(firms)}: {firms}")
# get_firms = FSS_call(firms, start, end)

#THIS GETS ME THE COMPANY DATA I NEED FROM FSS...ALL WE NEED FOR NEXT TIME
get_firms = FSS_call_chunk(firms, start, end)
get_firms = prop_neg_article(get_firms)

# COULD STOP HERE...BELOW FOR INDUSTRY METRICS....
INDUSTRY_METRICS = False
if INDUSTRY_METRICS:
  # MEAN SCORE WILL GIVE THE AGGREGATED DATA FOR THE INDUSTRY, WHICH IS LISTED RETAIL HERE ****
  mean_score = get_firms[['score_date', 'score']].groupby('score_date').mean().reset_index(drop=False)
  med_score = get_firms[['score_date', 'score']].groupby('score_date').median().reset_index(drop=False)
  min_score = get_firms.groupby('score_date')['score'].min().to_list()
  max_score = get_firms.groupby('score_date')['score'].max().to_list()

  mean_score.rename(columns={'score': 'mean_score'}, inplace=True)
  med_score.rename(columns={'score': 'med_score'}, inplace=True)
  # mean_score.index = pd.to_datetime(mean_score['score_date'])
  # med_score.index = pd.to_datetime(med_score['score_date'])

  mean_score = mean_score.merge(med_score, on='score_date', how='outer')

  # daily percent change
  mean_score['daily_pct_change_mean'] = mean_score['mean_score'].pct_change()
  mean_score['daily_pct_change_med'] = mean_score['med_score'].pct_change()

  # weekly change
  mean_score['7_day_change_mean'] = mean_score['mean_score'].shift(7)
  mean_score['7_day_comp'] = mean_score['score_date'].shift(7)
  mean_score['weekly_pct_change_mean'] = (mean_score['mean_score'] - mean_score['7_day_change_mean'])/ mean_score['7_day_change_mean']

  mean_score['7_day_change_med'] = mean_score['med_score'].shift(7)
  mean_score['weekly_pct_change_med'] = (mean_score['med_score'] - mean_score['7_day_change_med'])/ mean_score['7_day_change_med']

  # monthly change
  mean_score['30_day_change_mean'] = mean_score['mean_score'].shift(30)
  mean_score['30_day_comp'] = mean_score['score_date'].shift(30)
  mean_score['monthly_pct_change_mean'] = (mean_score['mean_score'] - mean_score['30_day_change_mean'])/ mean_score['30_day_change_mean']

  mean_score['30_day_change_med'] = mean_score['med_score'].shift(30)
  mean_score['monthly_pct_change_med'] = (mean_score['med_score'] - mean_score['30_day_change_med'])/ mean_score['30_day_change_med']

  # quarterly change
  mean_score['90_day_change_mean'] = mean_score['mean_score'].shift(90)
  mean_score['90_day_comp'] = mean_score['score_date'].shift(90)
  mean_score['quarterly_pct_change_mean'] = (mean_score['mean_score'] - mean_score['90_day_change_mean'])/ mean_score['90_day_change_mean']

  mean_score['90_day_change_med'] = mean_score['med_score'].shift(90)
  mean_score['quarterly_pct_change_med'] = (mean_score['med_score'] - mean_score['90_day_change_med'])/ mean_score['90_day_change_med']

  mean_score['min_score'] = min_score
  mean_score['max_score'] = max_score

  # out[ind.loc[i, 'industry']] = {'ind_score_changes': mean_score, # pd.DataFrame
  #                                 'company_codes': firms, # list
  #                                 'company_scores': get_firms, #pd.DataFrame
  #                                 'tickers': tickers #list
  #                                 }
  # print(f"DONE: {ind.loc[i, 'industry']}")
  # sleep(10)

# lastest_scores = get_firms.copy()
# test[test.score_date == '2026-02-26'] # some companies do not have the lastest date score

latest_scores = []

for c in get_firms._company_code.unique():
  df = get_firms[get_firms._company_code == c]
  df = df[df.score_date == df.score_date.max()]
  latest_scores.append(df)

latest_scores = pd.concat(latest_scores) # THIS IS WHERE WE LEFT OFF ... RETAIL LISTED FSS SCORES AND S&P DATA

SAVE = False
if SAVE:
  path = '/content/drive/MyDrive/FSS_files/FSS_Product_TESTS/'
  get_firms.to_csv(path + 'FSS_retail_listed_scores_quarterly.csv', index=False)
  latest_scores.to_csv(path + 'FSS_retail_listed_scores_lastDaily.csv', index=False)

latest_scores.rename(columns={'_company_code': 'company_code_FSS'}, inplace=True)
fss_sp_to_score = fss_retail_listed.merge(latest_scores, on='company_code_FSS', how='outer')
len(fss_sp_to_score)

fss_sp_to_score

fss_sp_to_score[['SP_ENTITY_NAME','IQ_EBIT_Y', 'IQ_EBIT_Q', 'IQ_RETAINED_EARNINGS_Y',
       'IQ_RETAINED_EARNINGS_Q']]

sandp.columns

# # THEN SCORE AND SORT ETC....
# fss_sp_to_score = fss_sp_to_score.replace({',': ''}, regex=True)

# # List of all columns used in your calculation
# cols_to_fix = [
#     'IQ_TOTAL_REV_Y', 'IQ_TOTAL_REV_Q', 'IQ_TOTAL_ASSETS_Y', 'IQ_TOTAL_ASSETS_Q',
#     'IQ_TOTAL_LIAB_Y', 'IQ_TOTAL_LIAB_Q', 'IQ_RETAINED_EARNINGS_Y', 'IQ_RETAINED_EARNINGS_Q',
#     'IQ_EBIT_Y', 'IQ_EBIT_Q', 'IQ_WORKING_CAP_Y', 'IQ_WORKING_CAP_Q', 'IQ_GP_Y','IQGP_Q', 'SP_MARKETCAP_Current'
# ]

# # Loop through and convert them all to numbers
# for col in cols_to_fix:
#     # Ensure the column is treated as a string first
#     fss_sp_to_score[col] = fss_sp_to_score[col].astype(str)

#     # Remove commas
#     fss_sp_to_score[col] = fss_sp_to_score[col].str.replace(',', '', regex=False)

#     # Handle Accounting Negatives: Replace "(100)" with "-100"
#     # This regex looks for anything inside () and puts a - in front
#     fss_sp_to_score[col] = fss_sp_to_score[col].str.replace(r'\((.*)\)', r'-\1', regex=True)

#     # Remove any remaining whitespace or currency symbols if they exist
#     fss_sp_to_score[col] = fss_sp_to_score[col].str.strip().str.replace('$', '', regex=False)

#     # Now safely convert to numeric
#     fss_sp_to_score[col] = pd.to_numeric(fss_sp_to_score[col], errors='coerce')

# # 1. Clean denominators to avoid division by zero errors
# fss_sp_to_score['IQ_TOTAL_LIAB_Y'] = fss_sp_to_score['IQ_TOTAL_LIAB_Y'].replace(0, np.nan)
# fss_sp_to_score['IQ_TOTAL_LIAB_Q'] = fss_sp_to_score['IQ_TOTAL_LIAB_Q'].replace(0, np.nan)
# fss_sp_to_score['IQ_TOTAL_ASSETS_Y'] = fss_sp_to_score['IQ_TOTAL_ASSETS_Y'].replace(0, np.nan)
# fss_sp_to_score['IQ_TOTAL_ASSETS_Q'] = fss_sp_to_score['IQ_TOTAL_ASSETS_Q'].replace(0, np.nan)

# # 2. Apply Proxy Logic (Filling gaps for EBIT and Retained Earnings)
# fss_sp_to_score['EBIT_PROXY_Y'] = fss_sp_to_score['IQ_EBIT_Y'].fillna(fss_sp_to_score['IQ_NET_INC_PARENT_Y'])
# fss_sp_to_score['EBIT_PROXY_Q'] = fss_sp_to_score['IQ_EBIT_Q'].fillna(fss_sp_to_score['IQ_NET_INC_PARENT_Q'])
# fss_sp_to_score['RE_PROXY_Y'] = fss_sp_to_score['IQ_RETAINED_EARNINGS_Y'].fillna(0)
# fss_sp_to_score['RE_PROXY_Q'] = fss_sp_to_score['IQ_RETAINED_EARNINGS_Q'].fillna(0)

# # Try to fill Revenue gaps with Gross Profit (if you have it)
# # Replace 'IQ_GROSS_PROFIT_Y' with your actual column name
# if 'IQ_GP_Y' in fss_sp_to_score.columns:
#     fss_sp_to_score['REV_PROXY_Y'] = fss_sp_to_score['IQ_TOTAL_REV_Y'].fillna(fss_sp_to_score['IQ_GP_Y'])
# else:
#     fss_sp_to_score['REV_PROXY_Y'] = fss_sp_to_score['IQ_TOTAL_REV_Y']

# if 'IQ_GP_Q' in fss_sp_to_score.columns:
#     fss_sp_to_score['REV_PROXY_Y'] = fss_sp_to_score['IQ_TOTAL_REV_Y'].fillna(fss_sp_to_score['IQ_GP_Y'])
# else:
#     fss_sp_to_score['REV_PROXY_Y'] = fss_sp_to_score['IQ_TOTAL_REV_Y']


# # --- YEARLY CALCULATION ---
# # Adjusting Market Cap (* 1000) and using Proxy columns
# fss_sp_to_score['Z_Yearly'] = (1.2 * (fss_sp_to_score['IQ_WORKING_CAP_Y'] / fss_sp_to_score['IQ_TOTAL_ASSETS_Y'])) + \
#                              (1.4 * (fss_sp_to_score['RE_PROXY_Y'] / fss_sp_to_score['IQ_TOTAL_ASSETS_Y'])) + \
#                              (3.3 * (fss_sp_to_score['EBIT_PROXY_Y'] / fss_sp_to_score['IQ_TOTAL_ASSETS_Y'])) + \
#                              (0.6 * (fss_sp_to_score['SP_MARKETCAP_Current'] * 1000 / fss_sp_to_score['IQ_TOTAL_LIAB_Y'])) + \
#                              (1.0 * (fss_sp_to_score['IQ_TOTAL_REV_Y'] / fss_sp_to_score['IQ_TOTAL_ASSETS_Y']))

# # --- QUARTERLY CALCULATION (Annualized) ---
# # Adjusting Market Cap (* 1000) and annualizing flow variables (* 4)
# fss_sp_to_score['Z_Quarterly'] = (1.2 * (fss_sp_to_score['IQ_WORKING_CAP_Q'] / fss_sp_to_score['IQ_TOTAL_ASSETS_Q'])) + \
#                                 (1.4 * (fss_sp_to_score['RE_PROXY_Q'] / fss_sp_to_score['IQ_TOTAL_ASSETS_Q'])) + \
#                                 (3.3 * (fss_sp_to_score['EBIT_PROXY_Q'] * 4 / fss_sp_to_score['IQ_TOTAL_ASSETS_Q'])) + \
#                                 (0.6 * (fss_sp_to_score['SP_MARKETCAP_Current'] * 1000 / fss_sp_to_score['IQ_TOTAL_LIAB_Q'])) + \
#                                 (1.0 * (fss_sp_to_score['IQ_TOTAL_REV_Q'] * 4 / fss_sp_to_score['IQ_TOTAL_ASSETS_Q']))

# 1. CLEANING STRINGS & CONVERTING TO NUMERIC
# Fixed 'IQGP_Q' typo to 'IQ_GP_Q' and added Net Income columns to cleanup list
cols_to_fix = [
    'IQ_TOTAL_REV_Y', 'IQ_TOTAL_REV_Q', 'IQ_TOTAL_ASSETS_Y', 'IQ_TOTAL_ASSETS_Q',
    'IQ_TOTAL_LIAB_Y', 'IQ_TOTAL_LIAB_Q', 'IQ_RETAINED_EARNINGS_Y', 'IQ_RETAINED_EARNINGS_Q',
    'IQ_EBIT_Y', 'IQ_EBIT_Q', 'IQ_WORKING_CAP_Y', 'IQ_WORKING_CAP_Q',
    'IQ_GP_Y', 'IQ_GP_Q', 'SP_MARKETCAP_Current', 'IQ_NET_INC_PARENT_Y', 'IQ_NET_INC_PARENT_Q'
]

for col in cols_to_fix:
    if col in fss_sp_to_score.columns:
        fss_sp_to_score[col] = fss_sp_to_score[col].astype(str)
        fss_sp_to_score[col] = fss_sp_to_score[col].str.replace(',', '', regex=False)
        fss_sp_to_score[col] = fss_sp_to_score[col].str.replace(r'\((.*)\)', r'-\1', regex=True)
        fss_sp_to_score[col] = fss_sp_to_score[col].str.strip().str.replace('$', '', regex=False)
        fss_sp_to_score[col] = pd.to_numeric(fss_sp_to_score[col], errors='coerce')

# 2. HANDLING ZERO DENOMINATORS & MISSING MARKET CAP
fss_sp_to_score['IQ_TOTAL_LIAB_Y'] = fss_sp_to_score['IQ_TOTAL_LIAB_Y'].replace(0, np.nan)
fss_sp_to_score['IQ_TOTAL_LIAB_Q'] = fss_sp_to_score['IQ_TOTAL_LIAB_Q'].replace(0, np.nan)
fss_sp_to_score['IQ_TOTAL_ASSETS_Y'] = fss_sp_to_score['IQ_TOTAL_ASSETS_Y'].replace(0, np.nan)
fss_sp_to_score['IQ_TOTAL_ASSETS_Q'] = fss_sp_to_score['IQ_TOTAL_ASSETS_Q'].replace(0, np.nan)

# Fix: If Market Cap is missing (delisted), treat as 0 so the formula doesn't break
fss_sp_to_score['SP_MARKETCAP_Current'] = fss_sp_to_score['SP_MARKETCAP_Current'].fillna(0)

# 3. APPLY PROXY LOGIC
# EBIT Proxy
fss_sp_to_score['EBIT_PROXY_Y'] = fss_sp_to_score['IQ_EBIT_Y'].fillna(fss_sp_to_score['IQ_NET_INC_PARENT_Y'])
fss_sp_to_score['EBIT_PROXY_Q'] = fss_sp_to_score['IQ_EBIT_Q'].fillna(fss_sp_to_score['IQ_NET_INC_PARENT_Q'])

# Retained Earnings Proxy
fss_sp_to_score['RE_PROXY_Y'] = fss_sp_to_score['IQ_RETAINED_EARNINGS_Y'].fillna(0)
fss_sp_to_score['RE_PROXY_Q'] = fss_sp_to_score['IQ_RETAINED_EARNINGS_Q'].fillna(0)

# Revenue Proxy (Filling missing Revenue with Gross Profit)
fss_sp_to_score['REV_PROXY_Y'] = fss_sp_to_score['IQ_TOTAL_REV_Y'].fillna(fss_sp_to_score['IQ_GP_Y'])
fss_sp_to_score['REV_PROXY_Q'] = fss_sp_to_score['IQ_TOTAL_REV_Q'].fillna(fss_sp_to_score['IQ_GP_Q'])

# 4. CALCULATIONS
# --- YEARLY ---
fss_sp_to_score['Z_Yearly'] = (1.2 * (fss_sp_to_score['IQ_WORKING_CAP_Y'] / fss_sp_to_score['IQ_TOTAL_ASSETS_Y'])) + \
                             (1.4 * (fss_sp_to_score['RE_PROXY_Y'] / fss_sp_to_score['IQ_TOTAL_ASSETS_Y'])) + \
                             (3.3 * (fss_sp_to_score['EBIT_PROXY_Y'] / fss_sp_to_score['IQ_TOTAL_ASSETS_Y'])) + \
                             (0.6 * (fss_sp_to_score['SP_MARKETCAP_Current'] * 1000 / fss_sp_to_score['IQ_TOTAL_LIAB_Y'])) + \
                             (1.0 * (fss_sp_to_score['REV_PROXY_Y'] / fss_sp_to_score['IQ_TOTAL_ASSETS_Y']))

# --- QUARTERLY ---
fss_sp_to_score['Z_Quarterly'] = (1.2 * (fss_sp_to_score['IQ_WORKING_CAP_Q'] / fss_sp_to_score['IQ_TOTAL_ASSETS_Q'])) + \
                                (1.4 * (fss_sp_to_score['RE_PROXY_Q'] / fss_sp_to_score['IQ_TOTAL_ASSETS_Q'])) + \
                                (3.3 * (fss_sp_to_score['EBIT_PROXY_Q'] * 4 / fss_sp_to_score['IQ_TOTAL_ASSETS_Q'])) + \
                                (0.6 * (fss_sp_to_score['SP_MARKETCAP_Current'] * 1000 / fss_sp_to_score['IQ_TOTAL_LIAB_Q'])) + \
                                (1.0 * (fss_sp_to_score['REV_PROXY_Q'] * 4 / fss_sp_to_score['IQ_TOTAL_ASSETS_Q']))

# to use for score:

'score', 'daily_percentage_change', 'weekly_percentage_change',
'Z_Yearly', 'Z_Quarterly', 'IQ_CURRENT_RATIO_Y', 'IQ_CURRENT_RATIO_Q',
'IQ_QUICK_RATIO_Y', 'IQ_QUICK_RATIO_Q', 'IQ_CASH_EQUIV_Y', 'IQ_CASH_EQUIV_Q',
'SP_HEADCOUNT_GROWTHRATE_2026',

fss_sp_to_score.columns

# Create a list of the 5 core components for Yearly
core_cols = ['IQ_WORKING_CAP_Y', 'IQ_TOTAL_ASSETS_Y', 'IQ_TOTAL_LIAB_Y', 'RE_PROXY_Y', 'EBIT_PROXY_Y', 'IQ_TOTAL_REV_Y', 'SP_MARKETCAP_Current']

# Filter for rows where Z_Yearly is still NaN
missing_data_report = fss_sp_to_score[fss_sp_to_score['Z_Yearly'].isna()]

# Show the columns for the first 10 missing companies to spot the NaN
missing_data_report[['company_name_FSS'] + core_cols] # Replace with your actual name column













# MOST CURRENT....DO NOT NEED, BUT KEEP FOR REFERENCE...

# for ch, chunk in enumerate(chunks):
for i_ in range(7,8):
    out = {}
    start = '2024-09-01'
    end = '2025-05-01'
    ind = chunks[i_].reset_index() # limited size from matched_fss_inds

    for i in range(len(ind)):
        firms = ind.loc[i, 'company_code']
        tickers = ind.loc[i, 'ticker']
        print(f"{len(firms)}: {firms}")
        # get_firms = FSS_call(firms, start, end)
        get_firms = FSS_call_chunk(firms, start, end) #<<<<-----------CALL IS HERE

        mean_score = get_firms[['score_date', 'score']].groupby('score_date').mean().reset_index(drop=False)
        med_score = get_firms[['score_date', 'score']].groupby('score_date').median().reset_index(drop=False)
        min_score = get_firms.groupby('score_date')['score'].min().to_list()
        max_score = get_firms.groupby('score_date')['score'].max().to_list()

        mean_score.rename(columns={'score': 'mean_score'}, inplace=True)
        med_score.rename(columns={'score': 'med_score'}, inplace=True)
        # mean_score.index = pd.to_datetime(mean_score['score_date'])
        # med_score.index = pd.to_datetime(med_score['score_date'])

        mean_score = mean_score.merge(med_score, on='score_date', how='outer')

        # daily percent change
        mean_score['daily_pct_change_mean'] = mean_score['mean_score'].pct_change()
        mean_score['daily_pct_change_med'] = mean_score['med_score'].pct_change()

        # weekly change
        mean_score['7_day_change_mean'] = mean_score['mean_score'].shift(7)
        mean_score['7_day_comp'] = mean_score['score_date'].shift(7)
        mean_score['weekly_pct_change_mean'] = (mean_score['mean_score'] - mean_score['7_day_change_mean'])/ mean_score['7_day_change_mean']

        mean_score['7_day_change_med'] = mean_score['med_score'].shift(7)
        mean_score['weekly_pct_change_med'] = (mean_score['med_score'] - mean_score['7_day_change_med'])/ mean_score['7_day_change_med']

        # monthly change
        mean_score['30_day_change_mean'] = mean_score['mean_score'].shift(30)
        mean_score['30_day_comp'] = mean_score['score_date'].shift(30)
        mean_score['monthly_pct_change_mean'] = (mean_score['mean_score'] - mean_score['30_day_change_mean'])/ mean_score['30_day_change_mean']

        mean_score['30_day_change_med'] = mean_score['med_score'].shift(30)
        mean_score['monthly_pct_change_med'] = (mean_score['med_score'] - mean_score['30_day_change_med'])/ mean_score['30_day_change_med']

        # quarterly change
        mean_score['90_day_change_mean'] = mean_score['mean_score'].shift(90)
        mean_score['90_day_comp'] = mean_score['score_date'].shift(90)
        mean_score['quarterly_pct_change_mean'] = (mean_score['mean_score'] - mean_score['90_day_change_mean'])/ mean_score['90_day_change_mean']

        mean_score['90_day_change_med'] = mean_score['med_score'].shift(90)
        mean_score['quarterly_pct_change_med'] = (mean_score['med_score'] - mean_score['90_day_change_med'])/ mean_score['90_day_change_med']

        mean_score['min_score'] = min_score
        mean_score['max_score'] = max_score

        out[ind.loc[i, 'industry']] = {'ind_score_changes': mean_score, # pd.DataFrame
                                        'company_codes': firms, # list
                                        'company_scores': get_firms, #pd.DataFrame
                                        'tickers': tickers #list
                                        }
        print(f"DONE: {ind.loc[i, 'industry']}")
        sleep(10)

    # save chunk
    new_out = save_json(out, file_path=f'/content/drive/MyDrive/FSS_files/fss_q1_chunk{i_}_rd4_company_data.json')
    print(f"......SAVED FILE PATH CHUNK {i_}......")

